default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: windmill_rails_development

test:
  <<: *default
  database: windmill_rails_test

production:
  <<: *default
  database: windmill_production
  username: windmill
  password: <%= ENV['WINDMILL_DATABASE_PASSWORD'] %>
